newsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls',namespace="polls")),
    url(r'^testapp/', include('testapp.urls',namespace="testapp")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from . import views
from django.conf.urls import url


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

testapp/urls.py
from . import views
from django.conf.urls import url
from django.conf.urls import include

urlpatterns = [
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^register/$', views.register, name='register'),
    url(r'^confirm/(?P<activation_key>\w+)/', views.register_confirm),
    
]

testapp/models.py
from django.db import models
from django.contrib.auth.models import User
import django.utils.timezone
# Create your models here.

class TutorialGroup(models.Model):
    group_name = models.CharField(max_length=200)
    group_order = models.IntegerField()

    def __unicode__(self):              # __str__ on Python 3
        return self.group_name

class Tutorial(models.Model):
    tutorial_name = models.CharField(max_length=200)
    tutorial_order = models.IntegerField(blank=True)
    depend_on = models.ForeignKey('self',null=True,blank=True)
    tutorial_group = models.ForeignKey(TutorialGroup)

    def __unicode__(self):              # __str__ on Python 3
        return self.tutorial_name

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    picture = models.ImageField(upload_to='profile_images', blank=True)
    shell_login = models.CharField(max_length=200, blank=True)
    activation_key = models.CharField(max_length=40, blank=True)
    key_expires = models.DateTimeField(default=django.utils.timezone.now)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

testapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('shell_login', 'picture')

testapp/views.py
from django.shortcuts import render, render_to_response, RequestContext,resolve_url, get_object_or_404
from django.views import generic
from .models import Tutorial, TutorialGroup, UserProfile
from .forms import UserProfileForm, UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
import hashlib, datetime, random
from django.utils import timezone

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'testapp/index.html'
    context_object_name = 'group_list'

    def get_queryset(self):
        return TutorialGroup.objects.order_by('group_order')

class DetailView(generic.DetailView):
    model = Tutorial
    template_name = 'testapp/detail.html'

def register(request):
    # Like before, get the request's context.
    context = RequestContext(request)

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()
            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.is_active=False
            user.save()

            username = user_form.cleaned_data['username']
            email = user_form.cleaned_data['email']

            salt = hashlib.sha1(str(random.random())).hexdigest()[:5]            
            activation_key = hashlib.sha1(salt+email).hexdigest()            
            key_expires = datetime.datetime.today() + datetime.timedelta(2)

             # Send email with activation key
            email_subject = 'Account confirmation'
            email_body = "Hey %s, thanks for signing up. To activate your account, click this link within \
            48hours http://127.0.0.1:8000/testapp/confirm/%s" % (username, activation_key)

            send_mail(email_subject, email_body, 'myemail@example.com',
                [email], fail_silently=False)

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.activation_key = activation_key
            profile.key_expires = key_expires

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print user_form.errors, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render_to_response(
            'registration/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered},
            context)

def register_confirm(request, activation_key):
    #check if user is already logged in and if he is redirect him to some other url, e.g. home
    if request.user.is_authenticated():
        HttpResponseRedirect('/home')

    # check if there is UserProfile which matches the activation key (if not then display 404)
    user_profile = get_object_or_404(UserProfile, activation_key=activation_key)

    #check if the activation key has expired, if it hase then render confirm_expired.html
    if user_profile.key_expires < timezone.now():
        return render_to_response('registration/confirm_expired.html')
    #if the key hasn't expired save user and set him as active and render some template to confirm activation
    user = user_profile.user
    user.is_active = True
    user.save()
    return render_to_response('registration/confirm.html')

def user_login(request):
    # Like before, obtain the context for the user's request.
    context = RequestContext(request)

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username = request.POST['username']
        password = request.POST['password']

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect(resolve_url('testapp:index'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render_to_response('registration/login.html', {}, context)

@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect(resolve_url('testapp:index'))

testapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Testapp</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="container theme-showcase" role="main">
            {% block header %}
            <div class="row">
                <div class="col-sm-4">
                    {% if user.is_authenticated %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                              <h3 class="panel-title">Welcome, {{ user.username }}.</h3>
                            </div>
                            <div class="panel-body">
                              Thanks for logging in. <a href="{% url 'testapp:logout' %}"><button type="button" class="btn btn-sm btn-warning">logout</button></a>
                            </div>
                        </div>
                        {% if user.is_superuser %}
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                  <h3 class="panel-title">Wow, you are admin.</h3>
                                </div>
                                <div class="panel-body">
                                    <a href="{% url 'admin:index' %}"><button type="button" class="btn btn-info">Rule the site.</button></a>
                                </div>
                            </div>
                        {% endif %}
                    {% else %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                              <h3 class="panel-title">Welcome, new user.</h3>
                            </div>
                            <div class="panel-body">
                                <a href="{% url 'testapp:login' %}">
                                    <button type="button" class="btn btn-sm btn-success">login</button>
                                </a> 
                                <a href="{% url 'testapp:register' %}">
                                    <button type="button" class="btn btn-sm btn-primary">register</button>
                                </a>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            {% endblock %}

            <div id="content">
                {% block content %}{% endblock %}
            </div>
        </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </body>
</html>